### PR TITLE
Adds a command to update Katello's nightly Pulp repository.

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
Opening this as a pull request to vet the logic before committing and running it since it makes large changes.

**Comment by jlsherrill** [comment]
Doesn't look like this handles the client repos (the normal katello-nightly-$DIST tags) and would need to handle the fedoras as well, any plans on adding support for that?

**Comment by ehelms** [comment]
That one is a bit tougher given we don't have a 1-1 correspondence to a pulp repository. I think what I could do is something like:

```
repodiff --new=https://fedorapeople.org/groups/katello/releases/yum/nightly/client/RHEL/6Server/x86_64/ --old=https://repos.fedorapeople.org/repos/pulp/pulp/stable/2.6/6Server/x86_64/ --archlist=noarch --simple
```

Which produces:

```
Loaded plugins: langpacks
setting up repos
setting up old repo https://repos.fedorapeople.org/repos/pulp/pulp/stable/2.6/6Server/x86_64/
setting up new repo https://fedorapeople.org/groups/katello/releases/yum/nightly/client/RHEL/6Server/x86_64/
performing the diff
New package: katello-agent-2.4.0-1.el6
             The Katello Agent

New package: katello-client-repos-2.3.0-3.el6
             Definition of yum repositories for Katello clients

Removed package:  createrepo-0.9.9-21.2.pulp.el6
Removed package:  gofer-package-2.6.1-1.el6
Removed package:  gofer-system-2.6.1-1.el6
Removed package:  gofer-virt-2.6.1-1.el6
Removed package:  pulp-admin-client-2.6.2-1.el6
Removed package:  pulp-agent-2.6.2-1.el6
Removed package:  pulp-consumer-client-2.6.2-1.el6
Removed package:  pulp-docker-admin-extensions-1.0.1-1.el6
Removed package:  pulp-docker-plugins-1.0.1-1.el6
Removed package:  pulp-nodes-admin-extensions-2.6.2-1.el6
Removed package:  pulp-nodes-child-2.6.2-1.el6
Removed package:  pulp-nodes-common-2.6.2-1.el6
Removed package:  pulp-nodes-consumer-extensions-2.6.2-1.el6
Removed package:  pulp-nodes-parent-2.6.2-1.el6
Removed package:  pulp-puppet-admin-extensions-2.6.2-1.el6
Removed package:  pulp-puppet-consumer-extensions-2.6.2-1.el6
Removed package:  pulp-puppet-handlers-2.6.2-1.el6
Removed package:  pulp-puppet-plugins-2.6.2-1.el6
Removed package:  pulp-puppet-tools-2.6.2-1.el6
Removed package:  pulp-python-admin-extensions-1.0.0-1.el6
Removed package:  pulp-python-plugins-1.0.0-1.el6
Removed package:  pulp-rpm-admin-extensions-2.6.2-1.el6
Removed package:  pulp-rpm-consumer-extensions-2.6.2-1.el6
Removed package:  pulp-rpm-plugins-2.6.2-1.el6
Removed package:  pulp-rpm-yumplugins-2.6.2-1.el6
Removed package:  pulp-selinux-2.6.2-1.el6
Removed package:  pulp-server-2.6.2-1.el6
Removed package:  python-amqp-doc-1.4.6-1.el6
Removed package:  python-celery-3.1.11-1.el6
Removed package:  python-crane-1.0.0-1.el6
Removed package:  python-kombu-3.0.24-7.pulp.el6
Removed package:  python-nectar-1.3.1-2.el6
Removed package:  python-pulp-bindings-2.6.2-1.el6
Removed package:  python-pulp-client-lib-2.6.2-1.el6
Removed package:  python-pulp-devel-2.6.2-1.el6
Removed package:  python-pulp-docker-common-1.0.1-1.el6
Removed package:  python-pulp-puppet-common-2.6.2-1.el6
Removed package:  python-pulp-python-common-1.0.0-1.el6
Removed package:  python-requests-2.4.3-1.el6
Removed package:  python-semantic-version-2.2.0-3.el6
Removed package:  qpid-cpp-client-devel-docs-0.26-9.el6

Updated Packages:

gofer: gofer-2.6.1-1.el6 ->  gofer-2.5.3-1.el6
pulp-rpm-handlers: pulp-rpm-handlers-2.6.2-1.el6 ->  pulp-rpm-handlers-2.6.0-1.el6
python-gofer: python-gofer-2.6.1-1.el6 ->  python-gofer-2.5.3-1.el6
python-gofer-amqp: python-gofer-amqp-2.6.1-1.el6 ->  python-gofer-amqp-2.5.3-1.el6
python-gofer-proton: python-gofer-proton-2.6.1-1.el6 ->  python-gofer-proton-2.5.3-1.el6
python-gofer-qpid: python-gofer-qpid-2.6.1-1.el6 ->  python-gofer-qpid-2.5.3-1.el6
python-pulp-agent-lib: python-pulp-agent-lib-2.6.2-1.el6 ->  python-pulp-agent-lib-2.6.0-1.el6
python-pulp-common: python-pulp-common-2.6.2-1.el6 ->  python-pulp-common-2.6.0-1.el6
python-pulp-rpm-common: python-pulp-rpm-common-2.6.2-1.el6 ->  python-pulp-rpm-common-2.6.0-1.el6
python-qpid: python-qpid-0.26-3.el6 ->  python-qpid-0.26-2.el6
python-qpid-common: python-qpid-common-0.26-3.el6 ->  python-qpid-common-0.26-2.el6

Summary:
Added Packages: 2
Removed Packages: 41
Modified Packages: 11
```

Where I'd want to tag the 'new package' and then update the 'updated packages' and ignore the 'Removed Packages' in this case. Would that make sense to you as well?

**Comment by jlsherrill** [comment]
haven't run it, but looks good to me.  ACK

**Pull request merged**
